baseurl = "https://www.manuelriccadonna.it"
title = "Tutt0l4nd"
theme = "tuttoland"
languagecode = "it"
defaultcontentlanguage = "it"

[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "github-dark"
  noClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "Manuel Riccadonna"
  info = "Photo · Video · Tech"
  description = "Blog personale di Manuel Riccadonna su tecnologia, fotografia e video. Da Bolzano."
  keywords = "blog,tecnologia,fotografia,video,Manuel Riccadonna,Bolzano"
  avatarurl = "img/avatar1.png"
  footercontent = "2026 © Manuel Riccadonna"

[[params.social]]
  name = "Instagram"
  url = "https://www.instagram.com/emmerrevideophoto/"

[[params.social]]
  name = "YouTube"
  url = "https://www.youtube.com/user/ttlg"

[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/manuel-riccadonna-20baa37/"

[[params.social]]
  name = "Facebook"
  url = "https://www.facebook.com/tuttologo"

[[params.social]]
  name = "X"
  url = "https://twitter.com/tuttologo79"

[[menu.main]]
  name = "Blog"
  weight = 1
  url = "/posts/"

[[menu.main]]
  name = "Gallery"
  weight = 2
  url = "/gallery/"

[[menu.main]]
  name = "Chi sono"
  weight = 3
  url = "/about/"

[[menu.main]]
  name = "Contatti"
  weight = 4
  url = "https://zfrmz.eu/n62KnbWckm3Qiko2PDtq"

[[menu.main]]
  name = "Privacy"
  weight = 5
  url = "/privacy/"