baseurl = "https://www.manuelriccadonna.it"
title = "Tutt0l4nd|T3ch&M0r3"
theme = "hugo-coder-portfolio"
# googleAnalytics = "UA-41615978-3"  # UA dismesso da Google nel 2023 - da aggiornare a GA4
languagecode = "it"
defaultcontentlanguage = "it"
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[pagination]
  pagerSize = 20

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    author = "Manuel Riccadonna"
    info = "Photo|Video|More"
    description = "Blog personale di Manuel Riccadonna su tecnologia, foto e video."
    keywords = "blog,tecnologia,fotografia,video,Manuel Riccadonna"
    avatarurl = "img/avatar1.png"
    footercontent = "2025 © Manuel Riccadonna"
    hideCredits = true
    hideCopyright = false
    custom_css = []
    itemscentered = true
    rtl = false
    snsShare = true
    thumbnail = "/images/tn.png"
    langseparator = "|"

[[params.social]]
    name = "Instagram"
    weight = 1
    url = "https://www.instagram.com/emmerrevideophoto/"
[[params.social]]
    name = "X"
    weight = 2
    url = "https://twitter.com/tuttologo79"
[[params.social]]
    name = "Facebook"
    weight = 3
    url = "https://www.facebook.com/tut
